# Generated by Django 3.1.5 on 2021-02-02 04:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210202_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 4, 0, 29, 197192, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
