# Generated by Django 3.1.5 on 2021-02-03 02:09

from django.db import migrations

def create_profiles(apps, schema_editor):
    '''
    We can't import the User model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    User = apps.get_model('auctions', 'User')
    UserProfile = apps.get_model('auctions', 'UserProfile')
    for u in User.objects.all():
        p = UserProfile(user=u, first_name=u.first_name, last_name=u.last_name)
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210203_0207'),
    ]

    operations = [
        migrations.RunPython(create_profiles),
    ]
