# Generated by Django 3.1.5 on 2021-02-04 02:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210204_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_closed',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date Closed'),
        ),
        migrations.AddField(
            model_name='listing',
            name='min_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Minimum Bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 2, 6, 23, 898314, tzinfo=utc), verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 2, 6, 23, 896081, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
