# Generated by Django 3.1.5 on 2021-02-04 04:03

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210204_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 4, 3, 47, 673816, tzinfo=utc), verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='min_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Minimum Bid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 4, 3, 47, 665005, tzinfo=utc), verbose_name='date joined'),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bid Amount')),
                ('date_bid', models.DateTimeField(default=datetime.datetime(2021, 2, 4, 4, 3, 47, 676006, tzinfo=utc), verbose_name='Date Bid')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ManyToManyField(related_name='bids', to='auctions.Listing')),
            ],
        ),
    ]
