# Generated by Django 3.1.5 on 2021-02-04 23:52

import auctions.models
import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210204_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bid Amount'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_bid',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 23, 52, 16, 944709, tzinfo=utc), verbose_name='Date Bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 23, 52, 16, 944162, tzinfo=utc), verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 23, 52, 16, 941957, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
