# Generated by Django 3.1.5 on 2021-02-04 23:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210204_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date_bid',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 23, 53, 21, 708950, tzinfo=utc), verbose_name='Date Bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 23, 53, 21, 708401, tzinfo=utc), verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 23, 53, 21, 706161, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
