# Generated by Django 3.1.5 on 2021-02-06 00:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210205_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_bid',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 0, 23, 49, 162884, tzinfo=utc), verbose_name='Date Bid'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='', verbose_name='Enter Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 0, 23, 49, 163920, tzinfo=utc), verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 0, 23, 49, 162164, tzinfo=utc), verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 0, 23, 49, 160063, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
