# Generated by Django 3.1.5 on 2021-02-06 02:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210206_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='watchlist',
            field=models.ManyToManyField(to='auctions.Listing'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_bid',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 2, 57, 26, 627437, tzinfo=utc), verbose_name='Date Bid'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 2, 57, 26, 628434, tzinfo=utc), verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 2, 57, 26, 625912, tzinfo=utc), verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 2, 57, 26, 623875, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
