# Generated by Django 3.1.5 on 2021-02-06 04:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210206_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date_closed',
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_bid',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 4, 40, 13, 304969, tzinfo=utc), verbose_name='Date Bid'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 4, 40, 13, 305972, tzinfo=utc), verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 4, 40, 13, 303494, tzinfo=utc), verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 4, 40, 13, 301723, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
